# Generated by Django 5.1.6 on 2025-04-20 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_animal_category_product_animals_product_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='favorite_count',
            field=models.IntegerField(default=0),
        ),
    ]
