# Generated by Django 5.1.6 on 2025-03-21 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0001_initial'),
        ('person', '0003_remove_person_is_active_remove_person_last_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.person'),
        ),
    ]
